---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ grafana.dir }}"
    - "{{ grafana.dashboards_dir }}"

- name: Assemble config files
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: docker-compose.yml
      dest: "{{ grafana.dir }}/docker-compose.yml"
    - src: datasources.yml
      dest: "{{ grafana.dir }}/datasources.yml"
    - src: dashboards.yml
      dest: "{{ grafana.dashboards_dir }}/dashboards.yml"
  notify: restart grafana

- name: Upload dashboards
  copy: src=files/dashboards/{{ item }} dest={{ grafana.dashboards_dir }}/{{ item }}
  with_items: "{{ grafana.dashboards }}"
