---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ nginx.services_dir }}/grafana"
    - /var/log/nginx/grafana

- name: Assemble nginx config
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
    - src: nginx/consul-template.conf.j2
      dest: "{{ nginx.templates_dir }}/grafana.conf"

- name: Assemble consul-template service config
  template:
    src: nginx/consul-template.service.j2
    dest: "{{ nginx.services_dir }}/grafana/run"
    mode: 'u+x'
